import Head from 'next/head'
// import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
// import SmallCard from '../components/SmallCard'
import SmallCard from '../components/SmallCard'
// import SmallCard2 from '../components/SmallCard2'
// import styles from '../styles/Home.module.css'

export default function Home({ explore, cardsData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
    <Banner />

    <main className='max-w-full mx-auto px-8 sm:px-10'>
      <section className='pt-6'>
        <h2 className='text-2xl font-semibold pb-1'>Explore Listings</h2>
      
      {/* Pull some data from a server - API endpoints */}
      <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>

        {explore?.map(({ img, distance, location}) => (
          <SmallCard
            key={img}
            img={img}
            distance={distance}
            location={location} />
        ))}
      </div>
      </section>

      <section>
        <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
       <div className='flex space-x-3 overflow-scroll scrollbar-hide p-5 -ml-3'>   
        {cardsData?.map(({img, title}) => (
          <MediumCard
            key={img}
            img={img}
            title={title} />
        ))}
      
        </div>
      </section>


      <LargeCard 
        img="https://links.papareact.com/4cj"
        title="The Greatest Outdoors"
        description="Wishlists curated by Airbnb."
        buttonText="Get Inspired"
      />

      
    </main>


    <Footer />
    </div>
  )
}

export async function getStaticProps() {
   const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G')
   const explore = await exploreData.json()

   const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").
   then((res) => 
      res.json()
   )

    return {
      props: {
        explore,
        cardsData
      }
    }
}
